import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';

export const marketplaceStyles = StyleSheet.create({
  container:          { flex: 1, backgroundColor: colors.background },
  header:             { flexDirection: 'row', justifyContent: 'space-between',
                        alignItems: 'center', padding: 20, paddingTop: 52,
                        backgroundColor: colors.surface,
                        borderBottomWidth: 1, borderBottomColor: colors.border },
  headerLeft:         { flex: 1, gap: 6 },
  backText:           { color: colors.gold, fontSize: 14 },
  headerTitle:        { fontSize: 20, color: colors.gold, fontWeight: '700' },
  tabs:               { flexDirection: 'row', backgroundColor: colors.surface,
                        borderBottomWidth: 1, borderBottomColor: colors.border },
  tab:                { flex: 1, paddingVertical: 12, alignItems: 'center' },
  tabActive:          { borderBottomWidth: 2, borderBottomColor: colors.gold },
  tabText:            { fontSize: 14, color: colors.textMuted, fontWeight: '600' },
  tabTextActive:      { color: colors.gold },
  scroll:             { flex: 1 },
  scrollContent:      { padding: 16, paddingBottom: 60 },
  empty:              { alignItems: 'center', paddingTop: 60 },
  emptyText:          { fontSize: 18, color: colors.textMuted, fontWeight: '600' },
  emptySubText:       { fontSize: 13, color: colors.textMuted, marginTop: 8 },

  listingCard:        { backgroundColor: colors.surface, borderRadius: 10,
                        borderWidth: 1, borderColor: colors.border,
                        padding: 14, marginBottom: 12 },
  listingHeader:      { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  listingIcon:        { fontSize: 24, marginRight: 10 },
  listingMeta:        { flex: 1 },
  listingTitle:       { fontSize: 15, color: colors.textPrimary, fontWeight: '700' },
  listingCategory:    { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  deleteBtn:          { color: colors.textMuted, fontSize: 16, padding: 4 },
  listingDesc:        { fontSize: 13, color: colors.textMuted,
                        lineHeight: 19, marginBottom: 10 },
  listingFooter:      { flexDirection: 'row', justifyContent: 'space-between',
                        alignItems: 'flex-end' },
  listingPrice:       { fontSize: 15, color: colors.gold, fontWeight: '700' },
  listingPriceMuted:  { fontSize: 13, color: colors.textMuted, fontStyle: 'italic' },
  listingSeller:      { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  listingDate:        { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  listingImage:       { width: '100%', height: 160, borderRadius: 8,
                        marginBottom: 10 },
  contactBtns:        { flexDirection: 'row', gap: 8 },
  contactBtn:         { width: 38, height: 38, borderRadius: 19,
                        backgroundColor: colors.surfaceDeep, borderWidth: 1,
                        borderColor: colors.border, alignItems: 'center',
                        justifyContent: 'center' },
  contactBtnText:     { fontSize: 18 },

  supplierIntro:      { fontSize: 13, color: colors.textMuted,
                        marginBottom: 16, lineHeight: 19 },
  supplierCard:       { backgroundColor: colors.surface, borderRadius: 10,
                        borderWidth: 1, borderColor: colors.border,
                        padding: 16, marginBottom: 12 },
  supplierHeader:     { flexDirection: 'row', justifyContent: 'space-between',
                        alignItems: 'center', marginBottom: 6 },
  supplierName:       { fontSize: 15, color: colors.textPrimary,
                        fontWeight: '700', flex: 1 },
  supplierLink:       { fontSize: 18, color: colors.gold },
  supplierRegion:     { fontSize: 12, color: colors.gold, marginBottom: 6 },
  supplierSpecialty:  { fontSize: 13, color: colors.textMuted,
                        lineHeight: 19, marginBottom: 4 },
  supplierUrl:        { fontSize: 11, color: colors.textMuted, fontStyle: 'italic' },
});

